
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
    - link: "mysql:root:chuan1992@tcp(127.0.0.1:3306)/rszai"
      descriptionTag: true
      tables: "attr_install,system_apps,attr_event_log"
