server:
  env: "dev"
  port: ":8802"
  serverRoot: "public"
  indexFiles: ["index.html"]

logger:
  path: "/tmp/logs"

database:
  logger:
    level: "all"
    stdout: true
    path: "/tmp/logs/sql"
  default:
    type: "mysql"
    host: "rszai-mysql"
    port: 3306
    user: "root"
    pass: "chuan1992"
    name: "rszai"
    charset: "utf8mb4"
    debug: true
    prefix: ""
    pool:
      maxIdle: 5
      maxOpen: 10
      maxLifetime: "300s"

redis:
  addr: "rszai-redis:6379"
  password: ""
  db: 0
  default:
    address: "rszai-redis:6379"
    db: 0
    pass: ""
    pool:
      maxIdle: 10
      maxActive: 100
      idleTimeout: "180s"

jwt:
  secret: "god-help-service-jwt-secret-key-2025"
  expire: "7776000s"  # 30 days

appstore:
  env: "sandbox"

gfcli:
  gen:
    dao:
      - link: "mysql:root:chuan1992@tcp(127.0.0.1:3306)/rszai"
        tables: "users"
        descriptionTag: true
