// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// attrDeviceDao is the data access object for the table attr_device.
// You can define custom methods on it to extend its functionality as needed.
type attrDeviceDao struct {
	*internal.AttrDeviceDao
}

var (
	// AttrDevice is a globally accessible object for table attr_device operations.
	AttrDevice = attrDeviceDao{internal.NewAttrDeviceDao()}
)

// Add your custom methods and functionality below.
