// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// attrAppleNotificationEventDao is the data access object for the table attr_apple_notification_event.
// You can define custom methods on it to extend its functionality as needed.
type attrAppleNotificationEventDao struct {
	*internal.AttrAppleNotificationEventDao
}

var (
	// AttrAppleNotificationEvent is a globally accessible object for table attr_apple_notification_event operations.
	AttrAppleNotificationEvent = attrAppleNotificationEventDao{internal.NewAttrAppleNotificationEventDao()}
)

// Add your custom methods and functionality below.
