// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// attrSubscriptionTransactionDao is the data access object for the table attr_subscription_transaction.
// You can define custom methods on it to extend its functionality as needed.
type attrSubscriptionTransactionDao struct {
	*internal.AttrSubscriptionTransactionDao
}

var (
	// AttrSubscriptionTransaction is a globally accessible object for table attr_subscription_transaction operations.
	AttrSubscriptionTransaction = attrSubscriptionTransactionDao{internal.NewAttrSubscriptionTransactionDao()}
)

// Add your custom methods and functionality below.
