// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// attrEventDao is the data access object for the table attr_event.
// You can define custom methods on it to extend its functionality as needed.
type attrEventDao struct {
	*internal.AttrEventDao
}

var (
	// AttrEvent is a globally accessible object for table attr_event operations.
	AttrEvent = attrEventDao{internal.NewAttrEventDao()}
)

// Add your custom methods and functionality below.
