// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// attrAppleNotificationEventsDao is the data access object for the table attr_apple_notification_events.
// You can define custom methods on it to extend its functionality as needed.
type attrAppleNotificationEventsDao struct {
	*internal.AttrAppleNotificationEventsDao
}

var (
	// AttrAppleNotificationEvents is a globally accessible object for table attr_apple_notification_events operations.
	AttrAppleNotificationEvents = attrAppleNotificationEventsDao{internal.NewAttrAppleNotificationEventsDao()}
)

// Add your custom methods and functionality below.
