// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// attrAppSubscriptionsDao is the data access object for the table attr_app_subscriptions.
// You can define custom methods on it to extend its functionality as needed.
type attrAppSubscriptionsDao struct {
	*internal.AttrAppSubscriptionsDao
}

var (
	// AttrAppSubscriptions is a globally accessible object for table attr_app_subscriptions operations.
	AttrAppSubscriptions = attrAppSubscriptionsDao{internal.NewAttrAppSubscriptionsDao()}
)

// Add your custom methods and functionality below.
