// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// attrEventLogDao is the data access object for the table attr_event_log.
// You can define custom methods on it to extend its functionality as needed.
type attrEventLogDao struct {
	*internal.AttrEventLogDao
}

var (
	// AttrEventLog is a globally accessible object for table attr_event_log operations.
	AttrEventLog = attrEventLogDao{internal.NewAttrEventLogDao()}
)

// Add your custom methods and functionality below.
