// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// attrInstallDao is the data access object for the table attr_install.
// You can define custom methods on it to extend its functionality as needed.
type attrInstallDao struct {
	*internal.AttrInstallDao
}

var (
	// AttrInstall is a globally accessible object for table attr_install operations.
	AttrInstall = attrInstallDao{internal.NewAttrInstallDao()}
)

// Add your custom methods and functionality below.
