// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// notificationEventsDao is the data access object for the table notification_events.
// You can define custom methods on it to extend its functionality as needed.
type notificationEventsDao struct {
	*internal.NotificationEventsDao
}

var (
	// NotificationEvents is a globally accessible object for table notification_events operations.
	NotificationEvents = notificationEventsDao{internal.NewNotificationEventsDao()}
)

// Add your custom methods and functionality below.
