// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// systemPermissionsDao is the data access object for the table system_permissions.
// You can define custom methods on it to extend its functionality as needed.
type systemPermissionsDao struct {
	*internal.SystemPermissionsDao
}

var (
	// SystemPermissions is a globally accessible object for table system_permissions operations.
	SystemPermissions = systemPermissionsDao{internal.NewSystemPermissionsDao()}
)

// Add your custom methods and functionality below.
