// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// systemAccountDao is the data access object for the table system_account.
// You can define custom methods on it to extend its functionality as needed.
type systemAccountDao struct {
	*internal.SystemAccountDao
}

var (
	// SystemAccount is a globally accessible object for table system_account operations.
	SystemAccount = systemAccountDao{internal.NewSystemAccountDao()}
)

// Add your custom methods and functionality below.
