// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// systemUsersDao is the data access object for the table system_users.
// You can define custom methods on it to extend its functionality as needed.
type systemUsersDao struct {
	*internal.SystemUsersDao
}

var (
	// SystemUsers is a globally accessible object for table system_users operations.
	SystemUsers = systemUsersDao{internal.NewSystemUsersDao()}
)

// Add your custom methods and functionality below.
