// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// systemRolesDao is the data access object for the table system_roles.
// You can define custom methods on it to extend its functionality as needed.
type systemRolesDao struct {
	*internal.SystemRolesDao
}

var (
	// SystemRoles is a globally accessible object for table system_roles operations.
	SystemRoles = systemRolesDao{internal.NewSystemRolesDao()}
)

// Add your custom methods and functionality below.
