// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// systemAppsDao is the data access object for the table system_apps.
// You can define custom methods on it to extend its functionality as needed.
type systemAppsDao struct {
	*internal.SystemAppsDao
}

var (
	// SystemApps is a globally accessible object for table system_apps operations.
	SystemApps = systemAppsDao{internal.NewSystemAppsDao()}
)

// Add your custom methods and functionality below.
