// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"god-help-service/internal/dao/internal"
)

// systemRolePermissionsDao is the data access object for the table system_role_permissions.
// You can define custom methods on it to extend its functionality as needed.
type systemRolePermissionsDao struct {
	*internal.SystemRolePermissionsDao
}

var (
	// SystemRolePermissions is a globally accessible object for table system_role_permissions operations.
	SystemRolePermissions = systemRolePermissionsDao{internal.NewSystemRolePermissionsDao()}
)

// Add your custom methods and functionality below.
